import React, { Component } from 'react';
import { connect } from 'react-redux'; // connect this component with redux

// selectBook function to be called on click of the list item
import { selectBook } from '../actions/index';

// importing bindActionCreator to make sure
// that the action generated by selectBook
// flows through all the different reducers
import { bindActionCreators } from 'redux';

// this is a smart componenet (or container) that cares about the state of
// this particular block (component; itself)

class BookList extends Component {
    renderList() {
        return this.props.books.map(book => {
            return (
                <li key={book.title}
                    className={"list-group-item"}
                    onClick={() => this.props.selectBook(book)}>
                    {book.title}
                </li>
            );
        });
    }

    render() {
        return (
            <ul className="list-group col-sm-4">
                {this.renderList()}
            </ul>
        );
    }
}

// it has store's current state as an argument
function mapStateToProps(state) {
    // whatever is returened will show up as props
    // in our BookList container
    return {
        books: state.books
    };
}

// again, anything returned from this should end up as props
function mapDispatchToProps(dispatch) {
    // whenever selectBook function is called, the result
    // should be passed on to all our reducers
    return bindActionCreators({
        selectBook: selectBook
    }, dispatch);
}

export default connect(mapStateToProps, mapDispatchToProps)(BookList);